# Generated by Django 5.1.3 on 2024-11-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_author_profile_pic_alter_book_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_pic',
            field=models.ImageField(default='authors/profile_default.jpg', upload_to='authors/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(default='books/default_book.jpg', upload_to='books/'),
        ),
    ]
