# Generated by Django 5.1.3 on 2024-11-28 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_userbook_delete_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserBook',
        ),
    ]
