# Generated by Django 5.1.3 on 2024-11-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reading_status',
            field=models.CharField(choices=[('L', 'Lu'), ('E', 'En cours'), ('A', 'À lire')], default='A', max_length=1),
        ),
    ]
