version: '3.8'

services:
  frontend:
    build:
      context: .  # Use the current directory as the build context
    environment:
      - NEXT_PUBLIC_API_URL=http://127.0.0.1:8000/api/v1
      - NEXT_PUBLIC_BASE_URL=http://127.0.0.1:8000
    command: npm start  # Start the Next.js app
    volumes:
      - .:/src  # Mount the current directory
    ports:
      - "3000:3000"
