# Generated by Django 5.1.3 on 2024-11-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_newuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='users/profile_default.jpg', null=True, upload_to='users/'),
        ),
    ]
